authentication/urls.py
from django.urls import path

from . import views

app_name = "authentication"

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='sign-up'),
    path('auth', views.auth, name='auth'),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path('', views.index, name='index'),
    #path('<str:id_fiscal>/profile/', views.profile, name='profile'),
    #path('create/', views.create, name='create'),
    path('create/', views.ClientCreateView.as_view(), name='create'),
    path('<slug:slug>/profile/', views.ClientProfileView.as_view(), name='profile'),
    path('<slug:slug>/profile/edit', views.ClientEditProfileView.as_view(), name='edit'),
]

djh_invoices_project/urls.py
from django.contrib import admin
from django.urls import path, include

#DEVELOPMENT ONLY
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authentication.urls")),
    path('client/', include("clients.urls")),
    path('invoices/', include("invoices.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #DEVELOPMENT ONLY

invoices/urls.py
from django.urls import path

from . import views

app_name = "invoices"

urlpatterns = [
    #path('list', views.list, name='list'),
    path('list/client/<slug:slug>/', views.ListInvoicesView.as_view(), name='list'),
    path('client/<slug:slug>/create/', views.InvoiceCreateView.as_view(), name='create'),
]

templates/_hero.html
<div class="section hero-section hero">
    <div class="container">
        <h1 class="heading heading-principal">{{title}}</h1>
        <h2 class="heading heading-secondary">Client: {{ client.nombres }} {{ client.apellidos }} - {{ client.ID_fiscal }}</h2>
    </div>
</div>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>
        {% block title %}
        {% endblock %}

    </title>
</head>
<body> 
    <nav class="section nav-header">
        <div class="brand-logo-wrapper">
            <img src="{% static 'assets/caravela-logo-light.png' %}" class="logo">
             
        </div>
        {% if client.activo %}
        <div class="button-wrapp">
            <a href="{% url 'invoices:create' slug=client_id_fiscal %}" class="btn link-button create-invoice-btn" title="Create Invoice">Create Invoice +</a>
        </div>
        {% endif %}
        <div class="nav-menu-wrapper">
            <ul class="nav-menu">
                <li class="menu-item"><a href="{% url 'clients:profile' slug=client_id_fiscal %}" class="menu-link">Profile</a></li>
                
                <li class="menu-item"><a href="{% url 'invoices:list' slug=client_id_fiscal %}" class="menu-link">Invoices</a></li>

                <li class="menu-item"><a href="{% url 'authentication:logout' %}" class="menu-link">Log out</a></li>
                
            </ul>
        </div>
    </nav>
    <main>
        {% block body %}
        {% endblock %}
    </main>
    <footer class="section">

    </footer>
</body>
</html>