authentication/urls.py
from django.urls import path

from . import views

app_name = "authentication"

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='sign-up'),
    path('auth', views.auth, name='auth'),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path('', views.index, name='index'),
    #path('<str:id_fiscal>/profile/', views.profile, name='profile'),
    #path('create/', views.create, name='create'),
    path('create/', views.ClientCreateView.as_view(), name='create'),
    path('<slug:slug>/profile/', views.ClientProfileView.as_view(), name='profile'),
    path('<slug:slug>/profile/edit', views.ClientEditProfileView.as_view(), name='edit'),
]

djh_invoices_project/urls.py
from django.contrib import admin
from django.urls import path, include

#DEVELOPMENT ONLY
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authentication.urls")),
    path('client/', include("clients.urls")),
    path('invoices/', include("invoices.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #DEVELOPMENT ONLY

clients/models.py
from django.db import models
from django.utils import timezone

class Cliente(models.Model):
    ID_fiscal = models.CharField(max_length=200, null=False)
    nombres = models.CharField(max_length=200, null=False)
    apellidos = models.CharField(max_length=200, null=False)
    empresa = models.CharField(max_length=200)
    correo = models.EmailField(max_length=200)
    telefono = models.CharField(max_length=200)
    direccion = models.CharField(max_length=500)
    contacto = models.CharField(max_length=200)
    telefono_contacto = models.CharField(max_length=200)
    mail_contacto = models.EmailField(max_length=200)
    pais = models.CharField(max_length=100, null=True)
    activo = models.BooleanField(default=False)
    fecha_creacion = models.DateTimeField('date published', default = timezone.now)
    fecha_inactivo = models.DateTimeField('desactived date', null=True)
    def __str__(self):
        return self.ID_fiscal

clients/forms.py
from django import forms
from django.forms import ModelForm
from .models import Cliente
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# class ClientsAddForm(forms.Form):
#     ID_fiscal = forms.CharField(label="Id Fiscal")
#     nombres = forms.CharField(label="Nombres")
#     apellidos = forms.CharField(label="Apellidos")
    

#     def clean_id_fiscal(self):
#         data = self.cleaned_data['ID_fiscal']

#         # Check if a date is not in the past.
#         if not data:
#             self.show_error('This field cant be empty')

#         # Remember to always return the cleaned data.
#         return data
#     def show_error(message):
#         raise ValidationError(_(message))

class ClientsAddForm(ModelForm):
    class Meta:
        model = Cliente
        exclude = ('activo', 'fecha_creacion','fecha_inactivo')
        #fields = ['ID_fiscal', 'nombres', 'apellidos']
        
    def clean_id_fiscal(self):
        data = self.cleaned_data['ID_fiscal']

        # Check if a date is not in the past.
        if not data:
            self.show_error('This field cant be empty')

        # Remember to always return the cleaned data.
        return data
    def show_error(message):
        raise ValidationError(_(message))


class ClientsEditForm(ModelForm):
    class Meta:
        model = Cliente
        exclude = ('activo', 'fecha_creacion', 'ID_fiscal','fecha_inactivo')
        #fields = ['ID_fiscal', 'nombres', 'apellidos']
        

    #def clean_id_fiscal(self):
        #data = self.cleaned_data['ID_fiscal']

        # Check if a date is not in the past.
        #if not data:
            #self.show_error('This field cant be empty')

        # Remember to always return the cleaned data.
        #return data
    def show_error(message):
        raise ValidationError(_(message))

clients/controllers.py
from .models import Cliente
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404
from .forms import ClientsAddForm

def save_client(f):
    try:
        #client = Cliente.objects.get(ID_fiscal=form.cleaned_data["ID_fiscal"])
        client = Cliente.objects.get(ID_fiscal=f.clean_id_fiscal())
    except Cliente.DoesNotExist:
        # obj = Cliente()
        # obj.ID_fiscal = form.clean_id_fiscal()
        # obj.nombres = form.cleaned_data["nombres"]
        # obj.apellidos = form.cleaned_data["apellidos"]
        # obj.save()
        created_user = f.save()
        context = {
            'error': False,
            'id_fiscal': created_user.ID_fiscal
        }
        return context
    else:
        return {'error':True, 'message_error': "Already exist a client with id_fiscal %s." % f.clean_id_fiscal()}

def update_client(f):
    if f.is_valid():
        updated_client = f.save()
        context = {
            'error': False,
            'id_fiscal': updated_client.ID_fiscal
        }
    else :
        context = {
            'error': True,
            'message_error': 'Validation error - plese try again'
        }
    return context

def get_client_by_idfiscal(id_fiscal):
    try:
        client = Cliente.objects.get(ID_fiscal=id_fiscal)
    except Cliente.DoesNotExist:
        raise Http404("Client does not exist")
    return client 

def get_client_by_pk(pk):
    try:
        client = Cliente.objects.get(pk=pk)
    except Cliente.DoesNotExist:
        raise Http404("Client does not exist")
    return client 

clients/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

#for class based views
from django.views import View
from .forms import ClientsAddForm, ClientsEditForm

from . import controllers, util

# class ClientValidation:
#     logged_user = {}
#     id_fiscal = ''
#     def __init__(self, req, idf):
#         self.request = req
#         self.id_fiscal = idf
#         self.logged_user = util.verify_login(req)

#     def validate_logged_client(self, reverse, HttpResponseRedirect):
#         if self.logged_user['logged_in'] is False:
#             return HttpResponseRedirect(reverse('authentication:login'))

#     def validate_permissions_client(self, render):
#         if self.logged_user['id_fiscal'] != self.id_fiscal:
#             return render(self.request, 'clients/no-permissions.html', {'title': 'Not permisions:', 'client_id_fiscal': self.logged_user['id_fiscal'], 'logged_user': self.logged_user})


class ClientProfileView(View):
    template_name = 'clients/profile.html'
    template_no_permisions = 'clients/no-permissions.html'

    def get(self, request, *args, **kwargs):
        
        logged_user = util.verify_login(request)
        if logged_user['logged_in'] is False:
            return HttpResponseRedirect(reverse('authentication:login'))
        if logged_user['id_fiscal'] != kwargs['slug']:
            return render(request, self.template_no_permisions, {'title': 'Not permisions:', 'client_id_fiscal': logged_user['id_fiscal'], 'logged_user': logged_user})
        # valid = ClientValidation(request, kwargs['slug'])
        # valid.validate_logged_client(reverse, HttpResponseRedirect)
        # valid.validate_permissions_client(render)

        client = controllers.get_client_by_idfiscal(kwargs['slug'])
        return render(request, self.template_name, {'client': client, 'title': 'Profile:', 'client_id_fiscal': client.ID_fiscal, 'logged_user': logged_user})

class ClientCreateView(View): 
    form_class = ClientsAddForm
    template_name = 'clients/create.html'
    created_template_name = 'clients/profile-created.html'

    def get(self, request, *args, **kwargs):
        logged_user = util.verify_login(request)
        if logged_user['logged_in'] :
            return HttpResponseRedirect(reverse('clients:profile', args=[logged_user['id_fiscal']]))

        form = self.form_class()
        return render(request, self.template_name, {'form': form, "title": 'Signup as client'})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # create the client 
            created_client = controllers.save_client(form)
            if created_client['error'] == False:
                return render(request, self.created_template_name, {'title': 'Account created waiting for activation', 'client_id_fiscal': created_client['id_fiscal']})
            else:
                return render(request, self.template_name, {"error": created_client['error'], "message_error": created_client['message_error'], "form": form, 'title': 'Error creating client'})
        else: 
            # If the form is invalid, re-render the page with existing information.
            return render(request, self.template_name, {"title": "Error - Invalid form data", "form": form})

def index(request):
    return HttpResponseRedirect(reverse("authentication:login"))

# def profile(request, id_fiscal):
#     client = controllers.get_client_by_idfiscal(id_fiscal)
#     return render(request, 'clients/profile.html', {'client': client, 'title': 'Profie:', 'client_id_fiscal': client.ID_fiscal})

# def create(request):
#     # Check if method is POST
#     if request.method == "POST":

#         # Take in the data the user submitted and save it as form
#         form = ClientsAddForm(request.POST)

#         # Check if form data is valid (server-side)
#         if form.is_valid():
#             # create the client 
#             created_client = controllers.save_client(form)
#             if created_client['error'] == False:
#                 return render(request, 'clients/profile-created.html', {'title': 'Account created waiting for activation', 'client_id_fiscal': created_client['id_fiscal']})
#             else:
#                 raise forms.ValidationError(
#                     created_client['message_error'],
#                 )
#         else: 
#             # If the form is invalid, re-render the page with existing information.
#             return render(request, "clients/create.html", {"title": "Error - Invalid form data", "form": form})

#     return render(request, "clients/create.html", {
#         "form": ClientsAddForm(),
#         "title": 'Signup as client'
#     })

# def edit(request):
#     return HttpResponse("Edit client page!")

class ClientEditProfileView(View):
    form_class = ClientsEditForm
    template_name = 'clients/edit.html'
    template_no_permisions = 'clients/no-permissions.html'

    def get(self, request, *args, **kwargs):
        logged_user = util.verify_login(request)
        if logged_user['logged_in'] is False:
            return HttpResponseRedirect(reverse('authentication:login'))
        if logged_user['id_fiscal'] != kwargs['slug']:
            return render(request, self.template_no_permisions, {'title': 'Not permisions:', 'client_id_fiscal': logged_user['id_fiscal'], 'logged_user': logged_user})
        
        
        client = controllers.get_client_by_idfiscal(kwargs['slug'])
        form = self.form_class(instance=client)
        return render(request, self.template_name, {'form': form, "title": 'Edit profile', 'client_id_fiscal': client.ID_fiscal, 'logged_user': logged_user})

    def post(self, request, *args, **kwargs):
        logged_user = util.verify_login(request)
        if logged_user['logged_in'] is False:
            return HttpResponseRedirect(reverse('authentication:login'))

        client = controllers.get_client_by_idfiscal(kwargs['slug'])
        form = self.form_class(request.POST, instance=client)
        created_client = controllers.update_client(form)

        if created_client['error']:
            return render(request, self.template_name, {"error": created_client['error'], "message_error": created_client['error'], "form": form, 'title': 'Error updating client','client_id_fiscal': client.ID_fiscal, 'logged_user': logged_user})
        else: 
            #return HttpResponse(created_client['id_fiscal'])
            return HttpResponseRedirect(reverse('clients:profile', args=[created_client['id_fiscal']]))

templates/clients/create.html
{% extends "layout-auth.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<div class="section auth-create-section"> 
    <div class="container">
    
        <form class="form" action="{% url 'clients:create' %}" method="post">
            <h1>Create client account</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
            {% if error %}
            <span class="form-error-message">
                {{message_error}}
            </span>
                
            {% endif %}
            <ul class="auth-menu">
                <li class="menu-item"><a href="{% url 'authentication:login' %}" class="menu-link">Login</a></li>
            </ul>
        </form>
    </div>
</div>
    
{% endblock %}

templates/clients/edit.html
{% extends "layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

{% include "../_hero.html" %}
<div class="section edit-client-section"> 
    <div class="container">
        <form action="{% url 'clients:edit' slug=client_id_fiscal  %}" method="post" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
            {% if error %}
                {{message_error}}
            {% endif %}
        </form>
    </div>
</div>
    
{% endblock %}

templates/clients/no-permissions.html
{% extends "layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

{% include "../_hero.html" %}
<div class="section edit-client-section"> 
    <div class="container">
        <div class="info-client no-permissions">
            <h2>You cant acces here</h2>
            <p>the page you try to see is blocked for you</p>
        </div>
    </div>
</div>
{% endblock %}

templates/clients/profile-created.html
{% extends "layout-auth.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<div class="section auth-client-created-section"> 
    <div class="container">
        <div class="info-client no-actived">
            <h2 style="color:rgb(1, 143, 1)">Client Account Created and waiting for activation</h2>
            <p>Your account is waiting for activation, please contact the admin</p>
        </div>
    </div>
</div>

    
{% endblock %}

templates/clients/profile.html
{% extends "layout.html" %}

{% block title %}
    {{title}} {{ client.nombres }} {{ client.apellidos }}
{% endblock %}

{% block body %}

{% include "../_hero.html" %}

{% if client.activo %}

<div class="section info-client-section"> 
    <div class="container">
        <div class="div-content form-content">
            <h4>ID FISCAL: {{ client.ID_fiscal }}</h4>
            <div class="info-client">
                <h3>Info Cliente:</h3>
                <ul class="info-client-list">
                    <li class="item-client-item">Pais: {{ client.pais }}</li>
                    <li class="item-client-item">Empresa: {{ client.empresa }}</li>
                    <li class="item-client-item">E-mail: {{ client.correo }}</li>
                    <li class="item-client-item">Telefono: {{ client.telefono }}</li>
                    <li class="item-client-item">Dirección: {{ client.direccion }}</li>
                    <li class="item-client-item">Fecha creado: {{ client.fecha_creacion }}</li>
                    <li class="item-client-item">Estado: {{ client.activo }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
    
<div class="section info-client-contact-section"> 
    <div class="container">
        <div class="info-contacto">
            <h3>Info Contacto:</h3>
            <ul class="info-client-list">
                <li class="item-client-item">Contacto: {{ client.contacto }}</li>
                <li class="item-client-item">Tel. Contacto: {{ client.telefono_contacto }}</li>
                <li class="item-client-item">E-mail Contacto: {{ client.mail_contacto }}</li>
            </ul>
        </div>
        <div class="actions">
            <ul class="actions-menu">
                <li class="action-item"><a href="{% url 'clients:edit' slug=client_id_fiscal %}" class="menu-link">Edit</a></li>
            </ul>
        </div>
    </div>
</div>
    
    

{% else %}
<div class="section info-client-contact-section"> 
    <div class="container">
        <div class="info-client no-actived">
            <h2>Account activation in process</h2>
            <p>Your account is waiting for activation, please contact the admin</p>
        </div>
    </div>
</div>
{% endif %}

    
{% endblock %}